// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function titleTemplate(title) {
  return "" + (String(title) + " | lafrenchtech-reason");
}

exports.titleTemplate = titleTemplate;
/* No side effect */
